//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClickCounterApp.Entities.Fortune
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        public int Id { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Message { get; set; }
        public string LuckyNumbers { get; set; }
        public string Type { get; set; }
    }
}
